#!/usr/bin/expect -f

set password "letsgoww"
set timeout 30

spawn ssh -o StrictHostKeyChecking=no terraq@TerraQuest-2.local "sudo systemctl restart terraquest.service"

expect {
    "Are you sure you want to continue connecting" { send "yes\r"; exp_continue }
    "password:" { send "$password\r"; exp_continue }
    "Password:" { send "$password\r"; exp_continue }
    eof
}

puts "\nService Restarted!"
